---
Resources:
  CyberDuckUser:
    Type: AWS::IAM::User
    Properties:
      UserName: CyberDuck
      Policies:
      - PolicyName: accessWarrenMiscFiles
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:AbortMultipartUpload
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucket
            - s3:ListBucketMultipartUploads
            - s3:PutObject
            - s3:DeleteObject
            Resource:
            - Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: WarrenMiscFiles
                - "/*"
            - Fn::Join:
              - ''
              - - 'arn:aws:s3:::'
                - Ref: WarrenMiscFiles
  WarrenMiscFiles:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: warren.misc.files
      LifecycleConfiguration:
        Rules:
        - Id: GlacierRule
          Status: Enabled
          Transitions:
          - TransitionInDays: '1'
            StorageClass: Glacier